package edu.zju.gis.dldsj.server.mapper;

import edu.zju.gis.dldsj.server.base.BaseMapper;
import edu.zju.gis.dldsj.server.entity.ParallelModel;
import edu.zju.gis.dldsj.server.entity.ParallelModelWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.Collection;
import java.util.List;

/**
 * @author yanlo yanlong_lee@qq.com
 * @version 1.0 2018/08/01
 * generated by mysql-generator
 */
public interface ParallelModelMapper {

    int deleteByPrimaryKey(String artifactId);

    int insert(ParallelModelWithBLOBs record);

    int insertSelective(ParallelModelWithBLOBs record);

    List<ParallelModel> selectAll();

    List<ParallelModel> selectByIdList(Collection<String> idList);

    List<String> getIdList();

    ParallelModelWithBLOBs selectByPrimaryKey(String artifactId);

    int updateByPrimaryKeySelective(ParallelModelWithBLOBs record);

    int updateByPrimaryKeyWithBLOBs(ParallelModelWithBLOBs record);

    int updateByPrimaryKey(ParallelModel record);

    default int updateByPrimaryKey(ParallelModelWithBLOBs record) {
        return updateByPrimaryKeyWithBLOBs(record);
    }

    List<ParallelModel> selectByUserId(@Param("userId") String userId);

    List<ParallelModel> selectPublicModel();

    List<ParallelModel> selectPublicByKeyword (String keys);

    List<ParallelModel> selectByKeywords(String userId, String keys);
}
